version: '2'

services:

  james:
    depends_on:
      - elasticsearch
      - cassandra
      - rabbitmq
    image: linagora/james-rabbitmq-project:branch-master
    container_name: james
    hostname: james.local
    volumes:
    - "/srv/bench-running-docker/james:/root/conf"
    environment:
      - GLOWROOT_ACTIVATED=TRUE
    ports:
      - "172.24.64.65:80:80"
      - "172.24.64.65:25:25"
      - "172.24.64.65:110:110"
      - "172.24.64.65:143:143"
      - "172.24.64.65:465:465"
      - "172.24.64.65:587:587"
      - "172.24.64.65:993:993"
      - "172.24.64.65:4000:4000"
      - "172.24.64.65:8000:8000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - discovery.type=single-node

  grafana:
    depends_on:
      - elasticsearch
    image: grafana/grafana
    ports:
      - "172.24.64.65:3000:3000"

  cassandra:
    image: cassandra:3.11.3

  rabbitmq:
    image: rabbitmq:3.8.1-management
